package com.mydomain.comercial_yuyo.model;
// Generated Oct 9, 2012 11:29:33 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE", schema = "PUBLIC", catalog = "TESTLOCAL", uniqueConstraints = @UniqueConstraint(columnNames = "EMAIL"))
public class Cliente implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellido;
	private String email;
	private BigDecimal saldo;
	private Set<Venta> ventas = new HashSet<Venta>(0);

	public Cliente() {
	}

	public Cliente(String nombre, String apellido, BigDecimal saldo) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.saldo = saldo;
	}
	public Cliente(String nombre, String apellido, String email,
			BigDecimal saldo, Set<Venta> ventas) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.saldo = saldo;
		this.ventas = ventas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", nullable = false)
	@NotNull
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO", nullable = false)
	@NotNull
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "EMAIL", unique = true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SALDO", nullable = false, precision = 20)
	@NotNull
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

}
