package com.mydomain.comercial_yuyo.model;
// Generated Oct 9, 2012 11:29:33 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleVentaId generated by hbm2java
 */
@Embeddable
public class DetalleVentaId implements java.io.Serializable {

	private int idProducto;
	private int idVenta;

	public DetalleVentaId() {
	}

	public DetalleVentaId(int idProducto, int idVenta) {
		this.idProducto = idProducto;
		this.idVenta = idVenta;
	}

	@Column(name = "ID_PRODUCTO", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "ID_VENTA", nullable = false)
	public int getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(int idVenta) {
		this.idVenta = idVenta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetalleVentaId))
			return false;
		DetalleVentaId castOther = (DetalleVentaId) other;

		return (this.getIdProducto() == castOther.getIdProducto())
				&& (this.getIdVenta() == castOther.getIdVenta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProducto();
		result = 37 * result + this.getIdVenta();
		return result;
	}

}
