package com.mydomain.comercial_yuyo.model;
// Generated Oct 9, 2012 11:29:33 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name = "VENTA", schema = "PUBLIC", catalog = "TESTLOCAL")
public class Venta implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private Date fecha;
	private BigDecimal monto;
	private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);

	public Venta() {
	}

	public Venta(Cliente cliente, Date fecha, BigDecimal monto) {
		this.cliente = cliente;
		this.fecha = fecha;
		this.monto = monto;
	}
	public Venta(Cliente cliente, Date fecha, BigDecimal monto,
			Set<DetalleVenta> detalleVentas) {
		this.cliente = cliente;
		this.fecha = fecha;
		this.monto = monto;
		this.detalleVentas = detalleVentas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENTE", nullable = false)
	@NotNull
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA", nullable = false, length = 23)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "MONTO", nullable = false, precision = 20)
	@NotNull
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "venta")
	public Set<DetalleVenta> getDetalleVentas() {
		return this.detalleVentas;
	}

	public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
		this.detalleVentas = detalleVentas;
	}

}
