DROP TABLE IF EXISTS DETALLE_VENTA;

DROP TABLE IF EXISTS VENTA;

DROP TABLE IF EXISTS PRODUCTO;

DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE PRODUCTO(
	ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CODIGO VARCHAR(64) NOT NULL UNIQUE,
	NOMBRE VARCHAR(255) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	PRECIO DECIMAL(20,2) NOT NULL
);

CREATE TABLE CLIENTE(
	ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(255) NOT NULL,
	APELLIDO VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) UNIQUE,
	SALDO DECIMAL(20,2) NOT NULL
);

CREATE TABLE VENTA(
	ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	ID_CLIENTE INTEGER NOT NULL,
	FECHA TIMESTAMP NOT NULL,
	MONTO DECIMAL(20,2) NOT NULL,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE DETALLE_VENTA(
	ID_PRODUCTO INTEGER NOT NULL,
	ID_VENTA INTEGER NOT NULL,
	CANTIDAD INTEGER NOT NULL,
	PRIMARY KEY(ID_PRODUCTO,ID_VENTA),
	FOREIGN KEY(ID_VENTA) REFERENCES VENTA(ID),
	FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);

INSERT INTO PRODUCTO(CODIGO, NOMBRE, DESCRIPCION, PRECIO) VALUES
('ST-AB-101','Pollos campeon','Algun pollo chino',17),
('ST-AB-102','Lomo borracho','carne con vino',25),
('ST-AC-103','Pumma','zapatillas paraguayas',150),
('ST-AC-104','Uvita','vino patero',20),
('ST-AD-105','yupicol','produccion nacional',5);

INSERT INTO CLIENTE(NOMBRE,APELLIDO,EMAIL,SALDO) VALUES
('Yalo','Cuellar','El propio',50000),
('Jorge','Rojas','emo',1000),
('Carlos','Bortolini','el encontrado',4000);
